language: java

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "mc1098-github"
    token:
      secure: "6eb959225ac261b0d1ad8f16af8da9a357fc5117"

jdk:
  - oraclejdk8

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
